# This is a sample build configuration for Clojure.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: clojure:lein-2.7.1

pipelines:
  branches:
  master:
    - step:
        script: # Modify the commands below to build your repository.
          - pip install boto3==1.3.0
          - lein deps
          - lein clean
          - lein jar
          - python ./build/s3_upload.py atmos-build-artefacts ./target/atmos-kernel*.jar atmos_kernel